version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client/:/app
      - /app/node_modules
    networks:
      - backend
    restart: "unless-stopped"
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server/:/app
      - /app/node_modules
    environment:
      - NODE_PATH=src
      - PORT=4000
    networks:
      - backend
    restart: "unless-stopped"

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
